#!/usr/bin/python3

import os
import pdb
import re
import sys
import gnureadline
import traceback
from collections import OrderedDict

from source import lib
from source import log
from source.classes import Algorithm, Variable
from source.functions import *

"""
deal with commands
"""
variables = OrderedDict()
output = []
grep_value = None
grep_method = None

while True:
    # print something from previous command if needed
    if output:
        #pdb.set_trace()
        for line in output:
            if grep_method == 'normal':
                if grep_value in line:
                    prynt(line)
            elif grep_method == 'regex':
                if re.search(grep_value, line):
                    prynt(line)
            else:
                prynt(line)
        output = []
    grep_value = None
    grep_method = None

    # get command
    try:
        cmd = input(log.COLOR_PURPLE + '*** ' + log.COLOR_NONE).strip()
    except EOFError: # Ctrl+D -> quit
        log.newline()
        lib.exit_program(None, None)
    
    if len(cmd) == 0:
        continue

    # is there ~~ or ~ ? that's grep, remember it
    quote_flags = {'\'': 0, '"': 0}
    for i, c in enumerate(cmd):
        if c in quote_flags.keys():
            quote_flags[c] ^= 0x1
            continue
        if c == '~' and not any(quote_flags.values()):
            #pdb.set_trace()
            try:
                if cmd[i+1] == '~':
                    grep_value = cmd[i+2:].strip()
                    grep_method = 'regex'
                else:
                    raise ValueError
            except:
                traceback.print_exc()
                grep_value = cmd[i+1:].strip()
                grep_method = 'normal'
            cmd = cmd[:i].strip()
            break
            
                

    # is this just a variable name? add to print queue
    if cmd in variables.keys():
        v = variables[cmd]
        if isinstance(v, Algorithm):
            v.detail()
        else:
            output.append('Bin:    ' + binary(v.as_raw()).decode())
            output.append('Int:    ' + v.as_int())
            output.append('Hex:    ' + v.as_hex())
            output.append('Raw:    ' + str(v.as_raw()))
            output.append('Base64: ' + v.as_base64())
        continue
    
    # or is this an assign?
    variable_name = None
    variable_match = re.match('^([A-Za-z0-9_-]+) *= *(.*)$', cmd)
    if variable_match:
        variable_name = variable_match.group(1).strip()
        cmd = variable_match.group(2).strip()
    

    # run following commands, return result into variable if defined
    #     else store in output and print on the next iteration
    # if no command matches, use the content as variable value (constant)



    # quit?
    if lib.quit_string(cmd):
        log.warn('Do you really want to quit? ', new_line=False)
        if lib.positive(input()):
            lib.exit_program(None, None)
        continue

    # test
    if cmd.startswith('test'):
        #venn(events, 'category == auth', 'severity == critical')
        list_overview(by_db_id, 'source', 'score >= 5')
        
        pass
        
    # list variables
    if cmd in ('var', 'vars', 'variables'):
        k_len = max([0] + [len(k) for k in variables.keys()])
        for k, v in variables.items():
            output.append('%*s  %s' % (k_len, k, str(v)))
            

    #################################
    # basic methods
    #################################
    # xor with any number of arguments
    elif cmd.startswith('xor '):
        arguments = cmd[4:].split()
        if arguments:
            result = variables[arguments[0]].as_raw()
            for a in arguments[1:]:
                if a in variables.keys():
                    result = xor(result, variables[a].as_raw())
                else:
                    log.err('The \'%s\' is not a variable.' % a)
            if variable_name:
                variables[variable_name] = Variable(result)
            else:
                output.append(result)
        else:
            log.err('You must provide arguments')

    ######################################
    # constant value OR bad command
    ######################################
    else:
        if variable_name:
            v = Variable(cmd, constant=True)
            variables[variable_name] = v
            log.info(variable_name, '=', (v if len(str(v)) <= 50 else str(v)[:28] + '...' + str(v)[-28:]))
        else:
            log.warn('Unknown command.')
############

